name: Check for Spammy Issue Comments

on:
  issue_comment:
    types: [created, edited]

permissions:
  issues: write

jobs:
  comment-filter:
    runs-on: ubuntu-latest
    steps:
    - uses: DecimalTurn/Comment-Filter@v0
